version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
      - /myapp/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
